version: '3.2'
services:
  hs:
    image: haskell:8.4.3
    tty: true
    volumes:
      - ./app:/app/app:Z
      - ./test:/app/test:Z
      - ./src:/app/src:Z
      - ./package.yaml:/app/package.yaml:Z
      - ./stack.yaml:/app/stack.yaml:Z
